image: themattrix/tox

cache:
    paths:
        - .tox

before_script:
    - echo "Setting Up...."

tests:
    script:
        - apt update
        - apt install -y libgl1-mesa-glx xvfb
        - pip install tox
        - xvfb-run -s "-screen 0 800x600x24" tox
