image: themattrix/tox

##########################################
##########################################
## We have to set the following env vars
## in the admin interface :
## - AWS_DEFAULT_REGION
## - BUCKET_NAME
## - AWS_ACCESS_KEY_ID
## - AWS_SECRET_ACCESS_KEY

stages:
    - tests
    - deploy_docs
cache:
    paths:
        - .tox

before_script:
    - echo "Setting Up...."

tests:
    stage: tests
    script:
        - apt update
        - apt install -y libgl1-mesa-glx xvfb
        - pip install tox
        - apt install -y graphviz xdg-utils
        - apt install -y libcairo2-dev libjpeg-dev libgif-dev
        - xvfb-run tox -v --recreate

build_and_deploy_docs:
    image: "python:latest"
    stage: deploy_docs
    only:
        - master
    dependencies:
        - tests
    before_script:
        - pip install awscli
        - apt update
        - apt install -y graphviz libgl1-mesa-glx xvfb xdg-utils
        - apt install -y libcairo2-dev libjpeg-dev libgif-dev
    script:
        - pip install -r requirements_dev.txt -r requirements_continuous_integration.txt
        - python setup.py install
        - xvfb-run make docs
        - aws s3 cp ./docs/_build/html/ s3://${BUCKET_NAME} --recursive
    environment:
        name: ${CI_COMMIT_REF_SLUG}
        url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/
